# Generated by Django 4.1.7 on 2023-06-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, max_length=1023, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
